Environment: Development
Author: Mohsen
Region: eu-central-1
ProjectName: vaquita

DeadLetterQueue:
    MaxReceiveCount: 3

Cognito:
    SelfSignUp: True
    DomainPrefix: vaquita
    AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile

Database:
    Name: images_labels
    DeletionProtection: False
    Scaling:
        AutoPause: True
        Min: 2
        Max: 8
        SecondsToAutoPause: 1800

Functions:
    DefaultSignedUrlExpirySeconds: "3600"
    DefaultMaxApiCallAttempts: "5"